import pool from '../config/database.js';
import { articleService } from '../services/articleService.js';

/**
 * Seed database with AI-generated articles
 * All articles are generated by AI - no hardcoded content
 * AI automatically selects topics for maximum variety
 */
async function seedDatabase() {
  try {
    console.log('Starting database seeding with AI-generated articles...\n');

    // Check if articles already exist
    const checkResult = await pool.query('SELECT COUNT(*) FROM articles');
    const count = parseInt(checkResult.rows[0].count);

    if (count > 0) {
      console.log(`Database already has ${count} articles. Skipping seed.`);
      process.exit(0);
    }

    // Generate 3 initial articles using AI
    const numberOfArticles = 3;
    console.log(`Generating ${numberOfArticles} articles using AI...\n`);

    for (let i = 0; i < numberOfArticles; i++) {
      console.log(`Generating article ${i + 1}/${numberOfArticles} (AI will choose topic)...`);

      // Pass null to let AI choose the topic automatically
      const article = await articleService.createArticle(null);
      console.log(`✓ Created: ${article.title}\n`);
    }

    console.log(`✓ Successfully seeded ${numberOfArticles} AI-generated articles!`);
    process.exit(0);
  } catch (error) {
    console.error('Seeding failed:', error.message);
    console.error(error.stack);
    process.exit(1);
  }
}

seedDatabase();
